### ISSUE TITLE
generated network files do not use renamed interface name

### ISSUE THREAD

**Issue by rnissl** [thkukuk/issue-generator#6]
In /etc/udev/rules.d/70-persistent-net.rules I do have entries like this one:
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="00:15:5d:85:04:21", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="ext1"

And /usr/lib/udev/rules.d/90-issue-generator.rules contains:
ACTION=="add", SUBSYSTEM=="net", RUN+="/usr/sbin/issue-generator network add $env{INTERFACE}"
ACTION=="remove", SUBSYSTEM=="net", RUN+="/usr/sbin/issue-generator network del $env{INTERFACE}"

The above action "add" will generate a file in /run/issue.d (for example /run/issue.d/70-eth1.conf) which uses the original interface name.

Hence, no interface adresses will be shown as issue.

**Comment by thkukuk** [comment]
Our 70-persistent-net.rules looks similar and it works there.
It sounds like you are running in e.g. this bug: https://github.com/systemd/systemd/issues/14935 ?

**Comment by rnissl** [comment]
So shouldn't  /usr/lib/udev/rules.d/90-issue-generator.rules then be changed like that:
ACTION=="add", SUBSYSTEM=="net", RUN+="/usr/sbin/issue-generator network add $name"
ACTION=="remove", SUBSYSTEM=="net", RUN+="/usr/sbin/issue-generator network del $name"

This file is part of https://ftp.opensuse.org/distribution/leap/15.3/repo/oss/noarch/issue-generator-1.7-1.17.noarch.rpm and hasn't been changed since 2019-05-05, while https://ftp.opensuse.org/update/leap/15.3/sle/x86_64/dracut-049.1+suse.238.gd8dbb075-150200.3.60.1.x86_64.rpm contains this change:

Wed Sep 29 14:00:00 2021
thomas.blume@suse.com
- Update to version 049.1+suse.207.g72a93d93:
  * fcoe/fcoe-genrules.sh: use $name instead of $env{INTERFACE} (bsc#1186260)
  * fix: /var/lib/nfs/statd/sm is /var/lib/nfs/sm on SUSE (bsc#1184970)

I'm going to upgrade to Leap 15.4 in January -- would be nice, if the issue could be fixed till then 😉

**Comment by thkukuk** [comment]
If you want to get something fixed in a Linux distribution, you have to report that bug against that Linux distribution, and not a random upstream github project and not even mentioning it there...

**Comment by thkukuk** [comment]
Since you did report this against this project/code: did you try the current code at all?
Since you have problems with renaming interfaces, I would bet that this code is missing in your version.

**Comment by rnissl** [comment]
The current code works better than the original distributed by Leap 15.3, i. e. it lists the 4 renamed interfaces + the 4 original interfaces eth0 ... eth3 (my adjusted regex is ^[^l]).

Using the original code with $name works as expected. Only the renamed interfaces get listet.

**Comment by thkukuk** [comment]
The current version from this project works fine for me in all cases. I assume you did not update the whole code but only the udev rule?
Anyways, your udev rule with the current git code works on Leap for me.
